version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /modules/SDN_Lab_5/node
    schedule:
      interval: weekly
    groups:
      node-base:
        patterns: ["*"]
