name: Feature request
description: Предложить улучшение
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Предложение
      description: Какую проблему решает изменение?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Варианты
      description: Какие альтернативы рассматривались?

