# $NAME is replaced by Clabgate with the immutable session namespace.
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: $NAME
  namespace: $NAME
spec:
  definition:
    containerlab: |-
      name: $NAME
      topology:
        nodes:
          r1:
            kind: linux
            image: ghcr.io/maintainer64/cms-labs-tasks-sdn-lab-5-node:latest
            image-pull-policy: Always
            env:
              LAB_PEER: 10.50.0.2
            ports:
              - 2201:22/tcp
              - 1161:161/udp
              - 18081:8080/tcp
          s1:
            kind: linux
            image: ghcr.io/maintainer64/cms-labs-tasks-sdn-lab-5-node:latest
            image-pull-policy: Always
            env:
              LAB_PEER: 10.50.0.1
            ports:
              - 2202:22/tcp
              - 1162:161/udp
              - 18082:8080/tcp
        links:
          - endpoints: ["r1:eth1", "s1:eth1"]
